graphs/urls.py
from django.urls import path, include
from .views import  SankeyView, TreeView, TableView, ScatterView, DonutView, Download, Redraw

app_name = 'graphs'
urlpatterns = [
    path('sankey/', SankeyView.as_view(), name='sankey'),
    path('tree/', TreeView.as_view(), name='tree'),
    path('table/', TableView.as_view(), name='table'),
    path('scatter/', ScatterView.as_view(), name='scatter'),
    path('donut/', DonutView.as_view(), name='donut'),
    path('<str:file_name>/<str:endpoint>', Download.as_view(), name='download'),
    path('redraw/<str:endpoint>/', Redraw.as_view(), name='redraw'),
    ]

norview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('graphs.urls', namespace='graphs')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stitch/urls.py
from django.urls import path, include
from .views import  AppendView

app_name = 'stitch'
urlpatterns = [
    path('append/', AppendView.as_view(), name='append'),
  
    ]

templates/components/append.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
{% if not data %}
    {% if not error %}
        <div class='row text-center'>
            <div class='col'>
                <h2 class='d-none mt-2 mb-1'>Append</h2>
                <img class='mt-2 mb-2'src="{% static 'media/append.gif' %}" height='70' width='100'/>
            </div>
        </div>
        <div class='row text-center '>
            <div class='col-lg-3 mx-auto mt-2'>
                <form class='form' enctype='multipart/form-data' action='' method='post'>
                    {% csrf_token %}
                    {{form.file_name}}
                    {{form.data_0}}
                    {{form.data_1}}
                    {{form.data_2}}
                    {{form.data_3}}
                    <button type='submit' class='btn btn primary mt-2' 
                     style="background-color: #000000; border-color:#FFD700 ; color: #FFD700">UPLOAD</button>
                    <button type='reset' class='btn btn-primary mt-2' 
                    style="background-color: white; border-color: red; color: black " >RESET</button>
                </form>
            </div>
        </div>
    {% else %}
        <g class='group'>
        <a type='button' class='btn btn-primary mt-2' href={% url 'graphs:redraw'  endpoint='append' %}
        style="background-color: white; border-color: red; color: black" >RE-APPEND</a>
        </g>
        <div class='error-msg' style='width:600;height:500'>
            {{error|safe}}
        </div>
    {% endif %}
{% elif not data.empty %}
<g class='group'>
    <a type='button' class='btn btn primary mt-2 ml-10' href={% url 'graphs:download' file_name=name endpoint='append' %} 
    style="background-color: #000000; border-color: #FFD700; color:#FFD700 ">DOWNLOAD</a>
        
    <a type='button' class='d-none btn btn-primary mt-2' href={% url 'graphs:redraw'  endpoint='append' %}
    style="background-color: green; border-color: red; color: black" >REDRAW</a>
    <div>
        <b>Append complete: {{data.shape}}</b>
        <b>Click download to retrieve your file</b>
    </div>
</g>
{% endif %}
{% endblock %}

templates/components/clean.html
{% extends 'base.html' %}

{% load static %}


<link rel="stylesheet" type="text/css" href="{% static 'styles/styles.css' %}"/>
{% block content %}
<div class='d-none row text-center mt-2'>
    <div class='col'>
        <h2><b>CHOOSE A SERVICE</b></h2>
    </div>
</div>

<div class='home-grid'>
     <div><img src="{% static 'media/append.gif' %}" height='120' width='120'/>
        <a type='button' class='btn btn primary' href={% url 'graphs:append' %} 
            style="background-color: #000000; border-color:#FFD700; color: #FFD700">
            <b>APPEND</b>
        </a>
    </div>
   
    <div><img class='mb-2' src="{% static 'media/split.gif' %}" height='120' width='120'/>
        <a type='button' class='btn btn primary' href={% url 'graphs:split' %} 
            style="background-color: #000000; border-color:#FFD700; color: #FFD700">
            <b>SPLIT</b>
        </a>
    </div>
    <div><img class='mb-2' src="{% static 'media/merger.gif' %}" height='120' width='120'/>
        <a type='button' class='btn btn primary' href={% url 'graphs:merge' %} 
            style="background-color: #000000; border-color:#FFD700; color: #FFD700">
            <b>MERGE</b>
        </a>
    </div>

</div>

{% endblock %}

templates/components/donut.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if not graph %}
<div class='row text-center'>
    <div class='col'>
        <h2 class='mt-2 mb-3'>Donut</h2>
        <img src="{% static 'media/donut.png' %}" />
        
    
    </div>
</div>
<div class='row text-center '>
    <div class='col-lg-3 mx-auto'>
        <form class='form' enctype='multipart/form-data' action='' method='post'>
            {% csrf_token %}
            {{form.file_name}}
            {{form.donuts}}
            {{form.aggregator}}
            {{form.title_text}}
            {{form.method}}
            {{form.data}}
             <button type='submit' class='btn btn primary mt-2' 
             style="background-color: #800080; border-color:green; color: white">Draw</button>
            <button type='reset' class='btn btn-primary mt-2' 
            style="background-color: white; border-color: red; color: black " >Reset</button>
        </form>
    </div>
</div>
{% elif graph %}
<div style='width:600;height:500'>
    <a type='button' class='btn btn primary mt-2' href={% url 'graphs:download' file_name=name endpoint='donut' %} 
    style="background-color: #800080; border-color:green; color: white">Download</a>
    
    <a type='button' class='btn btn-primary mt-2' href={% url 'graphs:redraw'  endpoint='donut' %}
    style="background-color: white; border-color: red; color: black" >Redraw</a>
    {{graph|safe}}
</div>
<script>
    const goBack = () => {
        window.history.back()
    }
</script>
{% endif %}
{% endblock %}




  
    

templates/components/merge.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if not data %}
    {% if not error %}
        <div class='row text-center'>
            <div class='col'>
                <h2 class='mt-2 mb-3'>Merge</h2>
                <img class='mt-2 mb-2' src="{% static 'media/merger.gif' %}" width='100', height='70'/>
            </div>
        </div>
        <div class='row text-center '>
            <div class='col-lg-3 mx-auto'>
                <form class='form' enctype='multipart/form-data' action='' method='post'>
                    {% csrf_token %}
                    {{form.file_name}}
                    {{form.left}}
                    {{form.right}}
                    {{form.join_type}}
                    {{form.data_0}}
                    {{form.data_1}}
                     <button type='submit' class='btn btn primary mt-2' 
                     style="background-color: #000000; border-color:#000000; color: #FFD700">SUMBIT</button>
                    <button type='reset' class='btn btn-primary mt-2' 
                    style="background-color: white; border-color: red; color: black " >RESET</button>
                </form>
            </div>
        </div>
    {% else %}
        <g class='group'>
        <a type='button' class='btn btn-primary mt-2' href={% url 'graphs:redraw'  endpoint='merge' %}
        style="background-color: white; border-color: red; color: black" >REDRAW</a>
        </g>
        <div class='error-msg' style='width:600;height:500'>
            {{error|safe}}
        </div>
    {% endif %}
{% elif not data.empty %}
<g class='group'>
    <a type='button' class='btn btn primary mt-2' href={% url 'graphs:download' file_name=name endpoint='merge' %} 
    style="background-color: #000000; border-color:#000000; color: #FFD700">DOWNLOAD</a>
    <a type='button' class='btn btn-primary mt-2' href={% url 'graphs:redraw'  endpoint='merge' %}
    style="background-color: white; border-color: red; color: black" >REDRAW</a>
    <div>
        <b>Merge complete: {{data.shape}}</b>
        <b>Click download to retrieve your file</b>
    </div>
</g>
{% endif %}
{% endblock %}




  
    

templates/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #800080;">
  <div class="container-fluid">
    <a class="navbar-brand" style="color:white" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" style="color:white" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="color:white" href="#">Features</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" style="color:white" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Analyzers</a>
           <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href=#>Aggregators</a></li>
            </ul>
           
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" style="color:white" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Visualizers
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href={% url 'graphs:sankey' %}>Sankey</a></li>
            <li><a class="dropdown-item" href={% url 'graphs:tree' %}>Tree</a></li>
            <li><a class="dropdown-item" href={% url 'graphs:table' %}>Table</a></li>
            <li><a class="dropdown-item" href={% url 'graphs:scatter' %}>Scatter</a></li>
            <li><a class="dropdown-item" href={% url 'graphs:donut' %}>Donut</a></li>


          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/components/sankeyform.html
{% extends 'base.html' %}
{% block content %}
{% if not graph %}
<div class='row text-center'>
    <div class='col'>
        <h2 class='mt-2 mb-3'>Sankey</h2>
    
    </div>
</div>
<div class='row text-center '>
    <div class='col-lg-3 mx-auto'>
        <form class='form' enctype='multipart/form-data' action='' method='post'>
            {% csrf_token %}
            {{form.file_name}}
            {{form.figure_title}}
            {{form.columns}}
            {{form.exclude_column}}
            {{form.exclude_value}}
            {{form.filter_column}}
            {{form.filter_value}}
            {{form.data}}
             <button type='submit' class='btn btn primary mt-2' 
             style="background-color: #800080; border-color:green; color: white">Draw</button>
            <button type='reset' class='btn btn-primary mt-2' 
            style="background-color: white; border-color: red; color: black " >Reset</button>
        </form>
    </div>
</div>
{% elif graph %}
<div style='width:600;height:500'>
    <a type='button' class='btn btn primary mt-2' href={% url 'graphs:download' file_name=name endpoint='sankey' %} 
    style="background-color: #800080; border-color:green; color: white">Download</a>
    
    <a type='button' class='btn btn-primary mt-2' href={% url 'graphs:redraw'  endpoint='sankey' %}
    style="background-color: white; border-color: red; color: black" >Redraw</a>
    {{graph|safe}}
</div>
<script>
    const goBack = () => {
        window.history.back()
    }
</script>
{% endif %}
{% endblock %}




  
    

templates/components/scatterform.html
{% extends 'base.html' %}
{% block content %}
{% if not graph %}
<div class='row text-center'>
    <div class='col'>
        <h2 class='mt-2 mb-3'>Scatter</h2>
    
    </div>
</div>
<div class='row text-center '>
    <div class='col-lg-3 mx-auto'>
        <form class='form' enctype='multipart/form-data' action='' method='post'>
            {% csrf_token %}
            {{form.file_name}}
            {{form.x}}
            {{form.y}}
            {{form.color}}
            {{form.size}}
            {{form.data}}
             <button type='submit' class='btn btn primary mt-2' 
             style="background-color: #800080; border-color:green; color: white">Draw</button>
            <button type='reset' class='btn btn-primary mt-2' 
            style="background-color: white; border-color: red; color: black " >Reset</button>
        </form>
    </div>
</div>
{% elif graph %}
<div style='width:600;height:500'>
    <a type='button' class='btn btn primary mt-2' href={% url 'graphs:download' file_name=name endpoint='scatter' %} 
    style="background-color: #800080; border-color:green; color: white">Download</a>
    
    <a type='button' class='btn btn-primary mt-2' href={% url 'graphs:redraw'  endpoint='scatter' %}
    style="background-color: white; border-color: red; color: black" >Redraw</a>
    {{graph|safe}}
</div>
<script>
    const goBack = () => {
        window.history.back()
    }
</script>
{% endif %}
{% endblock %}




  
    

templates/components/split.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if not data %}
    {% if not error %}
        <div class='row text-center'>
            <div class='col'>
                <h2 class='d-none mt-2 mb-2'>Split</h2>
                <img class='mt-2 mb-2' src="{% static 'media/split.gif' %}" width='70', height='70'/>
            </div>
        </div>
        <div class='row text-center '>
            <div class='col-lg-3 mx-auto mt-2'>
                <form class='form' enctype='multipart/form-data' action='' method='post'>
                    {% csrf_token %}
                    {{form.file_name}}
                    {{form.root}}
                    {{form.branches}}
                    {{form.token}}
                    {{form.data}}
                    <button type='sumbit' class='btn btn primary mt-2' 
                    style="background-color: #000000; border-color:#FFD700; color: #FFD700">SUMBIT</button>
                    <button type='reset' class='btn btn-primary mt-2' 
                    style="background-color: white; border-color: red; color: black " >Reset</button>
                </form>
            </div>
        </div>
    {% else %}
        <g class='group'>
        <a type='button' class='btn btn-primary mt-2' href={% url 'graphs:redraw'  endpoint='split' %}
        style="background-color: white; border-color: red; color: black" >RE-SPLIT</a>
        </g>
        <div class='error-msg' style='width:600;height:500'>
            {{error|safe}}
        </div>
    {% endif %}
{% elif not data.empty %}
<g class='group'>
    <a type='button' class='btn btn primary mt-2' href={% url 'graphs:download' file_name=name endpoint='split' %} 
    style="background-color: #000000; border-color: #FFD700; color: #FFD700">DOWNLOAD</a>
    
    <a type='button' class='btn btn-primary mt-2' href={% url 'graphs:redraw'  endpoint='split' %}
    style="background-color: white; border-color: red; color: black" >REDRAW</a>
    <div>
        <b>Split complete: {{data.shape}}</b>
        <b>Click download to retrieve your file</b>
    </div>
</g>
{% endif %}
{% endblock %}

templates/components/tableform.html
{% extends 'base.html' %}
{% block content %}
{% if not graph %}
<div class='row text-center'>
    <div class='col'>
        <h2 class='mt-2 mb-3'>Table</h2>
    
    </div>
</div>
<div class='row text-center '>
    <div class='col-md-3 mx-auto'>
        <form class='form' enctype='multipart/form-data' action='' method='post'>
            {% csrf_token %}
            {{form.file_name}}
            {{form.columns}}
            {{form.data}}
             <button type='submit' class='btn btn primary mt-2' 
             style="background-color: #800080; border-color:green; color: white">Draw</button>
            <button type='reset' class='btn btn-primary mt-2' 
            style="background-color: white; border-color: red; color: black " >Reset</button>
        </form>
    </div>
</div>
{% elif graph %}
<div style='width:600;height:1000'>
    <a type='button' class='btn btn primary mt-2' href={% url 'graphs:download' file_name=name endpoint='table' %} 
    style="background-color: #800080; border-color:green; color: white">Download</a>
    
    <a type='button' class='btn btn-primary mt-2' href={% url 'graphs:redraw'  endpoint='table' %}
    style="background-color: white; border-color: red; color: black" >Redraw</a>
    {{graph|safe}}
</div>
<script>
    const goBack = () => {
        window.history.back()
    }
</script>
{% endif %}
{% endblock %}

templates/components/treeform.html
{% extends 'base.html' %}
{% block content %}
{% if not graph %}
<div class='row text-center'>
    <div class='col'>
        <h2 class='mt-2 mb-3'>Tree</h2>
    
    </div>
</div>
<div class='row text-center '>
    <div class='col-md-3 mx-auto'>
        <form class='form' enctype='multipart/form-data' action='' method='post'>
            {% csrf_token %}
            {{form.file_name}}
            {{form.constant}}
            {{form.columns}}
            {{form.value}}
            {{form.hover_data}}
            {{form.data}}
             <button type='submit' class='btn btn primary mt-2' 
             style="background-color: #800080; border-color:green; color: white">Draw</button>
            <button type='reset' class='btn btn-primary mt-2' 
            style="background-color: white; border-color: red; color: black " >Reset</button>
        </form>
    </div>
</div>
{% elif graph %}
<div style='width:600;height:1000'>
    <a type='button' class='btn btn primary mt-2' href={% url 'graphs:download' file_name=name endpoint='tree' %} 
    style="background-color: #800080; border-color:green; color: white">Download</a>
    
    <a type='button' class='btn btn-primary mt-2' href={% url 'graphs:redraw'  endpoint='tree' %}
    style="background-color: white; border-color: red; color: black" >Redraw</a>
    {{graph|safe}}
</div>
<script>
    const goBack = () => {
        window.history.back()
    }
</script>
{% endif %}
{% endblock %}

templates/components/visualise.html
{% extends 'base.html' %}

{% load static %}


<link rel="stylesheet" type="text/css" href="{% static 'styles/styles.css' %}"/>
{% block content %}
<div class='d-none row text-center mt-2'>
    <div class='col'>
        <h2><b>CHOOSE A SERVICE</b></h2>
    </div>
</div>

<div class='home-grid'>
    <div><img class='mb-2' src="{% static 'media/sankey-2.gif' %}" height='120' width='120'/>
        <a type='button' class='btn btn primary' href={% url 'graphs:sankey' %} 
            style="background-color: #000000; border-color:#FFD700; color: #FFD700">
            <b>SANKEY</b>
        </a>
    </div>
    <div><img class='mb-2' src="{% static 'media/treemap.png' %}" height='120' width='120'/>
        <a type='button' class='btn btn primary' href={% url 'graphs:tree' %} 
            style="background-color: #000000; border-color:#FFD700; color: #FFD700">
            <b>TREEMAP</b>
        </a>
    </div>
    <div><img class='mb-2' src="{% static 'media/table.gif' %}" height='120' width='120'/>
        <a type='button' class='btn btn primary' href={% url 'graphs:table' %} 
            style="background-color: #000000; border-color:#FFD700; color: #FFD700">
            <b>TABLE</b>
        </a>
    </div>
   <div><img class='mb-2' src="{% static 'media/scatterplot.gif' %}" height='120' width='160'/>
         <a type='button' class='btn btn primary' href={% url 'graphs:scatter' %} 
            style="background-color: #000000; border-color:#FFD700; color: #FFD700">
            <b>SCATTERPLOT</b>
        </a>
    </div>
    <div><img class='mb-2' src="{% static 'media/doughnutChart3.png' %}" height='120' width='120'/>
        <a type='button' class='btn btn primary' href={% url 'graphs:donut' %} 
            style="background-color: #000000; border-color:#FFD700; color: #FFD700">
            <b>DONUT</b>
        </a>
    </div> 
</div>

{% endblock %}